print("hello, world")
print ("Hello, world!")
print ("Hello, world!")
print ("Hello, world!")
print ("hello, world!")
print ("hello, world!")
print ("hello, world!")
print ("hello, world!")
print("Hello, world!")
print ("Hello, world!")
